initial commit for session7
edselaguirre19/ASPNetCoreMasters pull request #6
Opened 2022-03-05 20:16 UTC by edselaguirre19

![session7](https://user-images.githubusercontent.com/91943090/156898683-faf7d4f5-6972-41fe-b348-fb2cf60c9306.gif)

2022-03-07 21:38 UTC, kevinatgithub commented on ASPNetCoreMastersToDoList/ASPNetCoreMastersToDoList.API/Filters/ValidationRequestFilter.cs
> +            if (id == null) return;
Please check if item exist here as stated in the requirements, Thanks!

2022-03-07 21:43 UTC, kevinatgithub requested changes
Please resolve comments, Thanks!

2022-03-13 20:12 UTC, edselaguirre19 commented
hi sir. already updated my code. thanks.

2022-03-14 05:30 UTC, kevinatgithub approved these changes

2022-03-14 05:30 UTC, merged